# Generated by Django 4.1.7 on 2023-02-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tolerancestackup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stackupstep',
            name='tolerance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
